### ISSUE TITLE
AttributeError: 'module' object has no attribute 'js' on Django1.8

### ISSUE THREAD

**Issue by Zorig** [mher/chartkick.py#28]
When i add `chartkick.js()` in `STATICFILES_DIRS` it gives me this error and can't start server
> AttributeError: 'module' object has no attribute 'js' 

and i removed it from `STATICFILES_DIRS` then run server again it gives me this error:

> TemplateSyntaxError: 'chartkick' is not a valid tag library: Template library chartkick not found, tried django.templatetags.chartkick,django.contrib.admin.templatetags.chartkick,django.contrib.staticfiles.templatetags.chartkick

sorry for rushing, but need to solve this immediately

**Comment by mher** [comment]
Please provide the full stack trace

**Comment by Zorig** [comment]
settings.py
```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tespa', #main app
    #thirdparty app
    'chartkick',
)
STATICFILES_DIRS = (
    chartkick.js(),   
    os.path.join(BASE_DIR, 'static'),
)
```
PLUS when i add `chartkick.js()` in `STATICFILES_DIRS` it gives 
> AttributeError: 'module' object has no attribute 'js'

html file
```{% extends 'base.html' %}
{% block title %}Тайлан{% endblock %}
{% block content %}
  {% load chartkick %}
  <div class="row">
   <div class="col-md-2"></div>
   <div class="col-md-8">
  <form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
      <label for="test">Тайлан гаргах тест сонгох</label>
      <select id="test" name="" class="form-control">
        <option value="">Сорил 001</option>
      </select>
    </div>
    <button type="submit" class="btn btn-info">Сонгох</button>
   </form>
</div>
<div class="col-md-2">
      <div class="chart">
        {% line_chart data %}
      </div>
   </div>
 </div>

<script src="{{ STATIC_URL }}js/jquery-2.1.3.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/highcharts.js"></script>
<script src="{{ STATIC_URL }}js/chartkick.js"></script>
{% endblock %}```

**Comment by mher** [comment]
`js` is a function defined in chartkick package (see `chartkick/__init__.py`). I don't know why it is not available in your setup. Try

    >>> import chartkick
    >>> chartkick.js()

You can replace chartkick.js() call with an actual js dir path.

**Comment by Zorig** [comment]
Yeah, i removed the chartkick.js() and set the chartkick.js path in html page. And then it gives 
> TemplateSyntaxError: 'chartkick' is not a valid tag library: Template library chartkick not found, tried django.templatetags.chartkick,django.contrib.admin.templatetags.chartkick,django.contrib.staticfiles.templatetags.chartkick

**Comment by Zorig** [comment]
@mher can you please test it on Django 1.8.2

**Comment by mher** [comment]
It works with  Django 1.8, 1.9
